// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'package:matrix/rust/event/event.dart';
import 'package:matrix/rust/frb_generated.dart';
import 'package:matrix/rust/lib.dart';

class SyncResponse {
  final String nextBatch;
  final Map<String, BigInt>? deviceOneTimeKeysCount;
  final SyncResponseToDevice? toDevice;
  final SyncResponseRooms? rooms;

  const SyncResponse({
    required this.nextBatch,
    this.deviceOneTimeKeysCount,
    this.toDevice,
    this.rooms,
  });

  @override
  int get hashCode =>
      nextBatch.hashCode ^
      deviceOneTimeKeysCount.hashCode ^
      toDevice.hashCode ^
      rooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponse &&
          runtimeType == other.runtimeType &&
          nextBatch == other.nextBatch &&
          deviceOneTimeKeysCount == other.deviceOneTimeKeysCount &&
          toDevice == other.toDevice &&
          rooms == other.rooms;
}

class SyncResponseInviteState {
  final List<StrippedStateEvent>? events;

  const SyncResponseInviteState({
    this.events,
  });

  @override
  int get hashCode => events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseInviteState &&
          runtimeType == other.runtimeType &&
          events == other.events;
}

class SyncResponseInvitedRoom {
  final SyncResponseInviteState? inviteState;

  const SyncResponseInvitedRoom({
    this.inviteState,
  });

  @override
  int get hashCode => inviteState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseInvitedRoom &&
          runtimeType == other.runtimeType &&
          inviteState == other.inviteState;
}

class SyncResponseJoinedRoom {
  final SyncResponseState? state;
  final SyncResponseTimeline? timeline;

  const SyncResponseJoinedRoom({
    this.state,
    this.timeline,
  });

  @override
  int get hashCode => state.hashCode ^ timeline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseJoinedRoom &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          timeline == other.timeline;
}

class SyncResponseRooms {
  final Map<String, SyncResponseJoinedRoom>? join;
  final Map<String, SyncResponseInvitedRoom>? invite;
  final Map<String, SyncResponseJoinedRoom>? leave;

  const SyncResponseRooms({
    this.join,
    this.invite,
    this.leave,
  });

  @override
  int get hashCode => join.hashCode ^ invite.hashCode ^ leave.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseRooms &&
          runtimeType == other.runtimeType &&
          join == other.join &&
          invite == other.invite &&
          leave == other.leave;
}

class SyncResponseState {
  final List<Event>? events;

  const SyncResponseState({
    this.events,
  });

  @override
  int get hashCode => events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseState &&
          runtimeType == other.runtimeType &&
          events == other.events;
}

class SyncResponseTimeline {
  final List<Event> events;
  final bool? limited;
  final String? prevBatch;

  const SyncResponseTimeline({
    required this.events,
    this.limited,
    this.prevBatch,
  });

  @override
  int get hashCode => events.hashCode ^ limited.hashCode ^ prevBatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseTimeline &&
          runtimeType == other.runtimeType &&
          events == other.events &&
          limited == other.limited &&
          prevBatch == other.prevBatch;
}

class SyncResponseToDevice {
  final List<ToDeviceEvent>? events;

  const SyncResponseToDevice({
    this.events,
  });

  @override
  int get hashCode => events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResponseToDevice &&
          runtimeType == other.runtimeType &&
          events == other.events;
}

class ToDeviceEvent {
  final String sender;
  final String eventType;
  final Map<String, Value> content;

  const ToDeviceEvent({
    required this.sender,
    required this.eventType,
    required this.content,
  });

  @override
  int get hashCode => sender.hashCode ^ eventType.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToDeviceEvent &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          eventType == other.eventType &&
          content == other.content;
}
