// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'package:matrix/rust/frb_generated.dart';
import 'package:matrix/rust/lib.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Event>>
abstract class Event implements RustOpaqueInterface {}

class StrippedStateEvent {
  final String sender;
  final String eventType;
  final String stateKey;
  final Map<String, Value> content;

  const StrippedStateEvent({
    required this.sender,
    required this.eventType,
    required this.stateKey,
    required this.content,
  });

  @override
  int get hashCode =>
      sender.hashCode ^
      eventType.hashCode ^
      stateKey.hashCode ^
      content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrippedStateEvent &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          eventType == other.eventType &&
          stateKey == other.stateKey &&
          content == other.content;
}
