// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'package:matrix/rust/frb_generated.dart';
import 'package:matrix/rust/lib.dart';

part 'event_content.freezed.dart';

class CreateContent {
  final String? creator;
  final String? encryptionAlgorithm;
  final bool? federate;
  final String? roomType;

  const CreateContent({
    this.creator,
    this.encryptionAlgorithm,
    this.federate,
    this.roomType,
  });

  @override
  int get hashCode =>
      creator.hashCode ^
      encryptionAlgorithm.hashCode ^
      federate.hashCode ^
      roomType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateContent &&
          runtimeType == other.runtimeType &&
          creator == other.creator &&
          encryptionAlgorithm == other.encryptionAlgorithm &&
          federate == other.federate &&
          roomType == other.roomType;
}

class EncryptedContent {
  final String algorithm;
  final String ciphertext;

  const EncryptedContent({
    required this.algorithm,
    required this.ciphertext,
  });

  @override
  int get hashCode => algorithm.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedContent &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          ciphertext == other.ciphertext;
}

class EncryptionContent {
  final String algorithm;

  const EncryptionContent({
    required this.algorithm,
  });

  @override
  int get hashCode => algorithm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptionContent &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm;
}

@freezed
sealed class EventContent with _$EventContent {
  const EventContent._();

  const factory EventContent.create(
    CreateContent field0,
  ) = EventContent_Create;
  const factory EventContent.encrypted(
    EncryptedContent field0,
  ) = EventContent_Encrypted;
  const factory EventContent.encryption(
    EncryptionContent field0,
  ) = EventContent_Encryption;
  const factory EventContent.member(
    MemberContent field0,
  ) = EventContent_Member;
  const factory EventContent.message(
    MessageContent field0,
  ) = EventContent_Message;
  const factory EventContent.badEncrypted(
    MessageContent field0,
  ) = EventContent_BadEncrypted;
  const factory EventContent.mlsCommit(
    MessageContent field0,
  ) = EventContent_MlsCommit;
  const factory EventContent.callMember(
    MessageContent field0,
  ) = EventContent_CallMember;
  const factory EventContent.callMemberEncryptionKeys(
    MessageContent field0,
  ) = EventContent_CallMemberEncryptionKeys;
  const factory EventContent.callMemberEncryptionKeysRequest(
    MessageContent field0,
  ) = EventContent_CallMemberEncryptionKeysRequest;
  const factory EventContent.callMemberEncryptionKeysSync(
    MessageContent field0,
  ) = EventContent_CallMemberEncryptionKeysSync;
}

class MemberContent {
  final String? avatarUrl;
  final String? displayname;
  final Membership membership;

  const MemberContent({
    this.avatarUrl,
    this.displayname,
    required this.membership,
  });

  @override
  int get hashCode =>
      avatarUrl.hashCode ^ displayname.hashCode ^ membership.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberContent &&
          runtimeType == other.runtimeType &&
          avatarUrl == other.avatarUrl &&
          displayname == other.displayname &&
          membership == other.membership;
}

enum Membership {
  join,
  leave,
  invite,
  block,
  knock,
  ;
}

@freezed
sealed class MessageContent with _$MessageContent {
  const MessageContent._();

  const factory MessageContent.callEncryptionKeys({
    required Map<String, Value?> body,
  }) = MessageContent_CallEncryptionKeys;
  const factory MessageContent.text({
    required String body,
  }) = MessageContent_Text;
  const factory MessageContent.image({
    required String body,
  }) = MessageContent_Image;
  const factory MessageContent.video({
    required String body,
  }) = MessageContent_Video;
  const factory MessageContent.sticker({
    required String body,
  }) = MessageContent_Sticker;
  const factory MessageContent.audio({
    required String body,
  }) = MessageContent_Audio;
  const factory MessageContent.notice({
    required String body,
  }) = MessageContent_Notice;
}
