# SPDX-FileCopyrightText: 2019-Present Famedly GmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: matrix_example_chat
description: A minimal example chat app for the Matrix Dart SDK.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  matrix:
    path: ../
  path: ^1.9.0
  path_provider: ^2.1.0
  provider: ^6.1.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
