include: package:famedly_dart_lints/analysis_options.yaml

linter:
  rules:
    # TODO: Enable these lints one after another and fix them
    non_constant_identifier_names: false
    avoid_void_async: false
    sort_pub_dependencies: false

dart_code_linter:
  rules:
    # TODO: Enable these lints one after another and fix them
    avoid-late-keyword: false
    avoid-redundant-async: false
    member-ordering: false
    prefer-match-file-name: false
    avoid-dynamic: false
    avoid-global-state: false
    avoid-unrelated-type-assertions: false
    avoid-unnecessary-type-casts: false
    prefer-first: false
    prefer-enums-by-name: false
    prefer-immediate-return: false

analyzer:
  exclude:
    - example/main.dart