// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'package:matrix/rust/api/matrix_api.dart';
import 'package:matrix/rust/api/models.dart';
import 'package:matrix/rust/client/crypto_public.dart';
import 'package:matrix/rust/client/room_list.dart';
import 'package:matrix/rust/crypto/mls_crypto.dart';
import 'package:matrix/rust/event/event.dart';
import 'package:matrix/rust/event/event_content.dart';
import 'package:matrix/rust/frb_generated.dart';
import 'package:matrix/rust/lib.dart';
import 'package:matrix/rust/room/room.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixClient>>
abstract class MatrixClient implements RustOpaqueInterface {
  String get accessToken;

  MatrixApi get api;

  MlsCrypto get crypto;

  String get deviceId;

  String get homeserverUrl;

  String? get prevBatch;

  Map<String, Room> get rooms;

  Map<String, EventContent> get sentMessagesCache;

  BigInt get transactionId;

  String get userId;

  set accessToken(String accessToken);

  set api(MatrixApi api);

  set crypto(MlsCrypto crypto);

  set deviceId(String deviceId);

  set homeserverUrl(String homeserverUrl);

  set prevBatch(String? prevBatch);

  set rooms(Map<String, Room> rooms);

  set sentMessagesCache(Map<String, EventContent> sentMessagesCache);

  set transactionId(BigInt transactionId);

  set userId(String userId);

  Future<List<String>> claimKeyPackages({required String userId});

  Future<String> createKeyPackage();

  Future<String> createMessage(
      {required String groupId, required String message});

  Future<MlsGroup> createMlsGroup({required String name});

  Future<String> createRoom();

  List<Room> getRoomList();

  Future<bool> groupIsFound({required String groupId});

  Future<void> invite({required String roomId, required String userId});

  Future<(String, String, String?)> inviteToMlsGroup(
      {required String groupId, required List<String> keyPackagesBase64});

  Future<String> joinRoom({required String roomId});

  Future<void> leaveRoom({required String roomId});

  static Future<MatrixClient> login(
          {required String homeserverUrl,
          required String username,
          required String password}) =>
      RustLib.instance.api.crateClientClientMatrixClientLogin(
          homeserverUrl: homeserverUrl, username: username, password: password);

  Future<void> mainThreadSleep();

  static Future<MatrixClient> matrixClientCrypto(
          {required String homeserverUrl,
          required String userId,
          required String deviceId}) =>
      RustLib.instance.api.crateClientClientMatrixClientMatrixClientCrypto(
          homeserverUrl: homeserverUrl, userId: userId, deviceId: deviceId);

  Future<void> mergePendingCommit({required String groupId});

  Future<DecryptedMessage> processMlsMessage({required String cipherText});

  Future<BigInt?> publishKeyPackages({required int count});

  Future<RoomEncryptionState?> roomEncryptionState({required String roomId});

  Future<Map<String, Room>> roomsSafe();

  Future<String> sendMessage({required String roomId, required String body});

  Future<String> sendMlsMessage(
      {required String roomId,
      required String mlsMessage,
      required EventContent eventContent,
      required bool waitForSyncAndMergeCommit});

  Future<void> sendWelcomeMessage(
      {required String userId, required String body});

  Future<SyncResponse> sync_({BigInt? timeout});

  Future<void> logout();
}
