// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'package:matrix/rust/frb_generated.dart';

part 'mls_crypto.freezed.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MlsCrypto>>
abstract class MlsCrypto implements RustOpaqueInterface {}

@freezed
sealed class DecryptedMessage with _$DecryptedMessage {
  const DecryptedMessage._();

  const factory DecryptedMessage.welcomeMessage({
    required String groupId,
  }) = DecryptedMessage_WelcomeMessage;
  const factory DecryptedMessage.stagedCommitMessage({
    String? senderName,
  }) = DecryptedMessage_StagedCommitMessage;
  const factory DecryptedMessage.proposal({
    String? senderName,
    required String message,
  }) = DecryptedMessage_Proposal;
  const factory DecryptedMessage.message({
    String? senderName,
    required String message,
  }) = DecryptedMessage_Message;
  const factory DecryptedMessage.unimplemented() =
      DecryptedMessage_Unimplemented;

  String content() =>
      RustLib.instance.api.crateCryptoMlsCryptoDecryptedMessageContent(
        that: this,
      );
}
