// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'package:matrix/rust/api/matrix_api.dart';
import 'package:matrix/rust/api/models.dart';
import 'package:matrix/rust/client/client.dart';
import 'package:matrix/rust/client/crypto_public.dart';
import 'package:matrix/rust/client/room_list.dart';
import 'package:matrix/rust/crypto/mls_crypto.dart';
import 'package:matrix/rust/event/event.dart';
import 'package:matrix/rust/event/event_content.dart';
import 'package:matrix/rust/frb_generated.dart';
import 'package:matrix/rust/lib.dart';
import 'package:matrix/rust/room/room.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_EventPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MatrixApiPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MatrixClientPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MlsCryptoPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MlsGroupPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RoomPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Event
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  MatrixApi
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          dynamic raw);

  @protected
  MatrixClient
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          dynamic raw);

  @protected
  MlsCrypto
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          dynamic raw);

  @protected
  MlsGroup
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          dynamic raw);

  @protected
  Room
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          dynamic raw);

  @protected
  Value
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  MatrixClient
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          dynamic raw);

  @protected
  MatrixClient
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          dynamic raw);

  @protected
  Map<String, Room>
      dco_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom_None(
          dynamic raw);

  @protected
  Map<String, Value>
      dco_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          dynamic raw);

  @protected
  Map<String, EventContent> dco_decode_Map_String_event_content_None(
      dynamic raw);

  @protected
  Map<String, Value?>
      dco_decode_Map_String_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          dynamic raw);

  @protected
  Map<String, SyncResponseInvitedRoom>
      dco_decode_Map_String_sync_response_invited_room_None(dynamic raw);

  @protected
  Map<String, SyncResponseJoinedRoom>
      dco_decode_Map_String_sync_response_joined_room_None(dynamic raw);

  @protected
  Map<String, BigInt> dco_decode_Map_String_u_64_None(dynamic raw);

  @protected
  Event
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  MatrixApi
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          dynamic raw);

  @protected
  MatrixClient
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          dynamic raw);

  @protected
  MlsCrypto
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          dynamic raw);

  @protected
  MlsGroup
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          dynamic raw);

  @protected
  Room
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          dynamic raw);

  @protected
  Value
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BigInt dco_decode_U128(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Value
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CreateContent dco_decode_box_autoadd_create_content(dynamic raw);

  @protected
  DecryptedMessage dco_decode_box_autoadd_decrypted_message(dynamic raw);

  @protected
  EncryptedContent dco_decode_box_autoadd_encrypted_content(dynamic raw);

  @protected
  EncryptionContent dco_decode_box_autoadd_encryption_content(dynamic raw);

  @protected
  EventContent dco_decode_box_autoadd_event_content(dynamic raw);

  @protected
  MemberContent dco_decode_box_autoadd_member_content(dynamic raw);

  @protected
  MessageContent dco_decode_box_autoadd_message_content(dynamic raw);

  @protected
  RoomEncryptionState dco_decode_box_autoadd_room_encryption_state(dynamic raw);

  @protected
  SyncResponseInviteState dco_decode_box_autoadd_sync_response_invite_state(
      dynamic raw);

  @protected
  SyncResponseRooms dco_decode_box_autoadd_sync_response_rooms(dynamic raw);

  @protected
  SyncResponseState dco_decode_box_autoadd_sync_response_state(dynamic raw);

  @protected
  SyncResponseTimeline dco_decode_box_autoadd_sync_response_timeline(
      dynamic raw);

  @protected
  SyncResponseToDevice dco_decode_box_autoadd_sync_response_to_device(
      dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CreateContent dco_decode_create_content(dynamic raw);

  @protected
  DecryptedMessage dco_decode_decrypted_message(dynamic raw);

  @protected
  EncryptedContent dco_decode_encrypted_content(dynamic raw);

  @protected
  EncryptionContent dco_decode_encryption_content(dynamic raw);

  @protected
  EventContent dco_decode_event_content(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<Event>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  List<Room>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, Room)>
      dco_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
          dynamic raw);

  @protected
  List<(String, Value)>
      dco_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          dynamic raw);

  @protected
  List<(String, EventContent)> dco_decode_list_record_string_event_content(
      dynamic raw);

  @protected
  List<(String, Value?)>
      dco_decode_list_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          dynamic raw);

  @protected
  List<(String, SyncResponseInvitedRoom)>
      dco_decode_list_record_string_sync_response_invited_room(dynamic raw);

  @protected
  List<(String, SyncResponseJoinedRoom)>
      dco_decode_list_record_string_sync_response_joined_room(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  List<StrippedStateEvent> dco_decode_list_stripped_state_event(dynamic raw);

  @protected
  List<ToDeviceEvent> dco_decode_list_to_device_event(dynamic raw);

  @protected
  MemberContent dco_decode_member_content(dynamic raw);

  @protected
  Membership dco_decode_membership(dynamic raw);

  @protected
  MessageContent dco_decode_message_content(dynamic raw);

  @protected
  Map<String, SyncResponseInvitedRoom>?
      dco_decode_opt_Map_String_sync_response_invited_room_None(dynamic raw);

  @protected
  Map<String, SyncResponseJoinedRoom>?
      dco_decode_opt_Map_String_sync_response_joined_room_None(dynamic raw);

  @protected
  Map<String, BigInt>? dco_decode_opt_Map_String_u_64_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Value?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  RoomEncryptionState? dco_decode_opt_box_autoadd_room_encryption_state(
      dynamic raw);

  @protected
  SyncResponseInviteState?
      dco_decode_opt_box_autoadd_sync_response_invite_state(dynamic raw);

  @protected
  SyncResponseRooms? dco_decode_opt_box_autoadd_sync_response_rooms(
      dynamic raw);

  @protected
  SyncResponseState? dco_decode_opt_box_autoadd_sync_response_state(
      dynamic raw);

  @protected
  SyncResponseTimeline? dco_decode_opt_box_autoadd_sync_response_timeline(
      dynamic raw);

  @protected
  SyncResponseToDevice? dco_decode_opt_box_autoadd_sync_response_to_device(
      dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<Event>?
      dco_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          dynamic raw);

  @protected
  List<StrippedStateEvent>? dco_decode_opt_list_stripped_state_event(
      dynamic raw);

  @protected
  List<ToDeviceEvent>? dco_decode_opt_list_to_device_event(dynamic raw);

  @protected
  (
    String,
    Room
  ) dco_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
      dynamic raw);

  @protected
  (
    String,
    Value
  ) dco_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
      dynamic raw);

  @protected
  (String, EventContent) dco_decode_record_string_event_content(dynamic raw);

  @protected
  (
    String,
    Value?
  ) dco_decode_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
      dynamic raw);

  @protected
  (String, String, String?) dco_decode_record_string_string_opt_string(
      dynamic raw);

  @protected
  (String, SyncResponseInvitedRoom)
      dco_decode_record_string_sync_response_invited_room(dynamic raw);

  @protected
  (String, SyncResponseJoinedRoom)
      dco_decode_record_string_sync_response_joined_room(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  RoomEncryptionState dco_decode_room_encryption_state(dynamic raw);

  @protected
  StrippedStateEvent dco_decode_stripped_state_event(dynamic raw);

  @protected
  SyncResponse dco_decode_sync_response(dynamic raw);

  @protected
  SyncResponseInviteState dco_decode_sync_response_invite_state(dynamic raw);

  @protected
  SyncResponseInvitedRoom dco_decode_sync_response_invited_room(dynamic raw);

  @protected
  SyncResponseJoinedRoom dco_decode_sync_response_joined_room(dynamic raw);

  @protected
  SyncResponseRooms dco_decode_sync_response_rooms(dynamic raw);

  @protected
  SyncResponseState dco_decode_sync_response_state(dynamic raw);

  @protected
  SyncResponseTimeline dco_decode_sync_response_timeline(dynamic raw);

  @protected
  SyncResponseToDevice dco_decode_sync_response_to_device(dynamic raw);

  @protected
  ToDeviceEvent dco_decode_to_device_event(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Event
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  MatrixApi
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          SseDeserializer deserializer);

  @protected
  MatrixClient
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          SseDeserializer deserializer);

  @protected
  MlsCrypto
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          SseDeserializer deserializer);

  @protected
  MlsGroup
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          SseDeserializer deserializer);

  @protected
  Room
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          SseDeserializer deserializer);

  @protected
  Value
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  MatrixClient
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          SseDeserializer deserializer);

  @protected
  MatrixClient
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          SseDeserializer deserializer);

  @protected
  Map<String, Room>
      sse_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom_None(
          SseDeserializer deserializer);

  @protected
  Map<String, Value>
      sse_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          SseDeserializer deserializer);

  @protected
  Map<String, EventContent> sse_decode_Map_String_event_content_None(
      SseDeserializer deserializer);

  @protected
  Map<String, Value?>
      sse_decode_Map_String_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          SseDeserializer deserializer);

  @protected
  Map<String, SyncResponseInvitedRoom>
      sse_decode_Map_String_sync_response_invited_room_None(
          SseDeserializer deserializer);

  @protected
  Map<String, SyncResponseJoinedRoom>
      sse_decode_Map_String_sync_response_joined_room_None(
          SseDeserializer deserializer);

  @protected
  Map<String, BigInt> sse_decode_Map_String_u_64_None(
      SseDeserializer deserializer);

  @protected
  Event
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  MatrixApi
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          SseDeserializer deserializer);

  @protected
  MatrixClient
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          SseDeserializer deserializer);

  @protected
  MlsCrypto
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          SseDeserializer deserializer);

  @protected
  MlsGroup
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          SseDeserializer deserializer);

  @protected
  Room
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          SseDeserializer deserializer);

  @protected
  Value
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Value
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CreateContent sse_decode_box_autoadd_create_content(
      SseDeserializer deserializer);

  @protected
  DecryptedMessage sse_decode_box_autoadd_decrypted_message(
      SseDeserializer deserializer);

  @protected
  EncryptedContent sse_decode_box_autoadd_encrypted_content(
      SseDeserializer deserializer);

  @protected
  EncryptionContent sse_decode_box_autoadd_encryption_content(
      SseDeserializer deserializer);

  @protected
  EventContent sse_decode_box_autoadd_event_content(
      SseDeserializer deserializer);

  @protected
  MemberContent sse_decode_box_autoadd_member_content(
      SseDeserializer deserializer);

  @protected
  MessageContent sse_decode_box_autoadd_message_content(
      SseDeserializer deserializer);

  @protected
  RoomEncryptionState sse_decode_box_autoadd_room_encryption_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseInviteState sse_decode_box_autoadd_sync_response_invite_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseRooms sse_decode_box_autoadd_sync_response_rooms(
      SseDeserializer deserializer);

  @protected
  SyncResponseState sse_decode_box_autoadd_sync_response_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseTimeline sse_decode_box_autoadd_sync_response_timeline(
      SseDeserializer deserializer);

  @protected
  SyncResponseToDevice sse_decode_box_autoadd_sync_response_to_device(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CreateContent sse_decode_create_content(SseDeserializer deserializer);

  @protected
  DecryptedMessage sse_decode_decrypted_message(SseDeserializer deserializer);

  @protected
  EncryptedContent sse_decode_encrypted_content(SseDeserializer deserializer);

  @protected
  EncryptionContent sse_decode_encryption_content(SseDeserializer deserializer);

  @protected
  EventContent sse_decode_event_content(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<Event>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  List<Room>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, Room)>
      sse_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
          SseDeserializer deserializer);

  @protected
  List<(String, Value)>
      sse_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          SseDeserializer deserializer);

  @protected
  List<(String, EventContent)> sse_decode_list_record_string_event_content(
      SseDeserializer deserializer);

  @protected
  List<(String, Value?)>
      sse_decode_list_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          SseDeserializer deserializer);

  @protected
  List<(String, SyncResponseInvitedRoom)>
      sse_decode_list_record_string_sync_response_invited_room(
          SseDeserializer deserializer);

  @protected
  List<(String, SyncResponseJoinedRoom)>
      sse_decode_list_record_string_sync_response_joined_room(
          SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
      SseDeserializer deserializer);

  @protected
  List<StrippedStateEvent> sse_decode_list_stripped_state_event(
      SseDeserializer deserializer);

  @protected
  List<ToDeviceEvent> sse_decode_list_to_device_event(
      SseDeserializer deserializer);

  @protected
  MemberContent sse_decode_member_content(SseDeserializer deserializer);

  @protected
  Membership sse_decode_membership(SseDeserializer deserializer);

  @protected
  MessageContent sse_decode_message_content(SseDeserializer deserializer);

  @protected
  Map<String, SyncResponseInvitedRoom>?
      sse_decode_opt_Map_String_sync_response_invited_room_None(
          SseDeserializer deserializer);

  @protected
  Map<String, SyncResponseJoinedRoom>?
      sse_decode_opt_Map_String_sync_response_joined_room_None(
          SseDeserializer deserializer);

  @protected
  Map<String, BigInt>? sse_decode_opt_Map_String_u_64_None(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Value?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  RoomEncryptionState? sse_decode_opt_box_autoadd_room_encryption_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseInviteState?
      sse_decode_opt_box_autoadd_sync_response_invite_state(
          SseDeserializer deserializer);

  @protected
  SyncResponseRooms? sse_decode_opt_box_autoadd_sync_response_rooms(
      SseDeserializer deserializer);

  @protected
  SyncResponseState? sse_decode_opt_box_autoadd_sync_response_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseTimeline? sse_decode_opt_box_autoadd_sync_response_timeline(
      SseDeserializer deserializer);

  @protected
  SyncResponseToDevice? sse_decode_opt_box_autoadd_sync_response_to_device(
      SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<Event>?
      sse_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          SseDeserializer deserializer);

  @protected
  List<StrippedStateEvent>? sse_decode_opt_list_stripped_state_event(
      SseDeserializer deserializer);

  @protected
  List<ToDeviceEvent>? sse_decode_opt_list_to_device_event(
      SseDeserializer deserializer);

  @protected
  (
    String,
    Room
  ) sse_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
      SseDeserializer deserializer);

  @protected
  (
    String,
    Value
  ) sse_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
      SseDeserializer deserializer);

  @protected
  (String, EventContent) sse_decode_record_string_event_content(
      SseDeserializer deserializer);

  @protected
  (
    String,
    Value?
  ) sse_decode_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
      SseDeserializer deserializer);

  @protected
  (String, String, String?) sse_decode_record_string_string_opt_string(
      SseDeserializer deserializer);

  @protected
  (String, SyncResponseInvitedRoom)
      sse_decode_record_string_sync_response_invited_room(
          SseDeserializer deserializer);

  @protected
  (String, SyncResponseJoinedRoom)
      sse_decode_record_string_sync_response_joined_room(
          SseDeserializer deserializer);

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  RoomEncryptionState sse_decode_room_encryption_state(
      SseDeserializer deserializer);

  @protected
  StrippedStateEvent sse_decode_stripped_state_event(
      SseDeserializer deserializer);

  @protected
  SyncResponse sse_decode_sync_response(SseDeserializer deserializer);

  @protected
  SyncResponseInviteState sse_decode_sync_response_invite_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseInvitedRoom sse_decode_sync_response_invited_room(
      SseDeserializer deserializer);

  @protected
  SyncResponseJoinedRoom sse_decode_sync_response_joined_room(
      SseDeserializer deserializer);

  @protected
  SyncResponseRooms sse_decode_sync_response_rooms(
      SseDeserializer deserializer);

  @protected
  SyncResponseState sse_decode_sync_response_state(
      SseDeserializer deserializer);

  @protected
  SyncResponseTimeline sse_decode_sync_response_timeline(
      SseDeserializer deserializer);

  @protected
  SyncResponseToDevice sse_decode_sync_response_to_device(
      SseDeserializer deserializer);

  @protected
  ToDeviceEvent sse_decode_to_device_event(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  JSAny
      cst_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom_None(
          Map<String, Room> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  JSAny
      cst_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          Map<String, Value> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  JSAny cst_encode_Map_String_event_content_None(
      Map<String, EventContent> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_event_content(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  JSAny
      cst_encode_Map_String_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          Map<String, Value?> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  JSAny cst_encode_Map_String_sync_response_invited_room_None(
      Map<String, SyncResponseInvitedRoom> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_sync_response_invited_room(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  JSAny cst_encode_Map_String_sync_response_joined_room_None(
      Map<String, SyncResponseJoinedRoom> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_sync_response_joined_room(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  JSAny cst_encode_Map_String_u_64_None(Map<String, BigInt> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_record_string_u_64(
        raw.entries.map((e) => (e.key, e.value)).toList());
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  String cst_encode_U128(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(raw.toString());
  }

  @protected
  int cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      Value raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        raw);
  }

  @protected
  bool cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_bool(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_create_content(CreateContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_create_content(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_decrypted_message(DecryptedMessage raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_decrypted_message(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_encrypted_content(EncryptedContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_encrypted_content(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_encryption_content(EncryptionContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_encryption_content(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_event_content(EventContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_event_content(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_member_content(MemberContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_member_content(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_message_content(MessageContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_message_content(raw);
  }

  @protected
  int cst_encode_box_autoadd_room_encryption_state(RoomEncryptionState raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_room_encryption_state(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sync_response_invite_state(
      SyncResponseInviteState raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sync_response_invite_state(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sync_response_rooms(SyncResponseRooms raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sync_response_rooms(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sync_response_state(SyncResponseState raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sync_response_state(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sync_response_timeline(
      SyncResponseTimeline raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sync_response_timeline(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_sync_response_to_device(
      SyncResponseToDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_sync_response_to_device(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_64(raw);
  }

  @protected
  JSAny cst_encode_create_content(CreateContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.creator),
      cst_encode_opt_String(raw.encryptionAlgorithm),
      cst_encode_opt_box_autoadd_bool(raw.federate),
      cst_encode_opt_String(raw.roomType)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_decrypted_message(DecryptedMessage raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is DecryptedMessage_WelcomeMessage) {
      return [0, cst_encode_String(raw.groupId)].jsify()!;
    }
    if (raw is DecryptedMessage_StagedCommitMessage) {
      return [1, cst_encode_opt_String(raw.senderName)].jsify()!;
    }
    if (raw is DecryptedMessage_Proposal) {
      return [
        2,
        cst_encode_opt_String(raw.senderName),
        cst_encode_String(raw.message)
      ].jsify()!;
    }
    if (raw is DecryptedMessage_Message) {
      return [
        3,
        cst_encode_opt_String(raw.senderName),
        cst_encode_String(raw.message)
      ].jsify()!;
    }
    if (raw is DecryptedMessage_Unimplemented) {
      return [4].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_encrypted_content(EncryptedContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.algorithm), cst_encode_String(raw.ciphertext)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_encryption_content(EncryptionContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.algorithm)].jsify()!;
  }

  @protected
  JSAny cst_encode_event_content(EventContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is EventContent_Create) {
      return [0, cst_encode_box_autoadd_create_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_Encrypted) {
      return [1, cst_encode_box_autoadd_encrypted_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_Encryption) {
      return [2, cst_encode_box_autoadd_encryption_content(raw.field0)]
          .jsify()!;
    }
    if (raw is EventContent_Member) {
      return [3, cst_encode_box_autoadd_member_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_Message) {
      return [4, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_BadEncrypted) {
      return [5, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_MlsCommit) {
      return [6, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_CallMember) {
      return [7, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_CallMemberEncryptionKeys) {
      return [8, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_CallMemberEncryptionKeysRequest) {
      return [9, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }
    if (raw is EventContent_CallMemberEncryptionKeysSync) {
      return [10, cst_encode_box_autoadd_message_content(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          List<Event> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
            cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          List<Room> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
            cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny
      cst_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
          List<(String, Room)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
            cst_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny
      cst_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          List<(String, Value)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
            cst_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_string_event_content(
      List<(String, EventContent)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_record_string_event_content).toList().jsify()!;
  }

  @protected
  JSAny
      cst_encode_list_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          List<(String, Value?)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
            cst_encode_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_string_sync_response_invited_room(
      List<(String, SyncResponseInvitedRoom)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(cst_encode_record_string_sync_response_invited_room)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_string_sync_response_joined_room(
      List<(String, SyncResponseJoinedRoom)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(cst_encode_record_string_sync_response_joined_room)
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_string_u_64(List<(String, BigInt)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_record_string_u_64).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_stripped_state_event(List<StrippedStateEvent> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_stripped_state_event).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_to_device_event(List<ToDeviceEvent> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_to_device_event).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_member_content(MemberContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_String(raw.avatarUrl),
      cst_encode_opt_String(raw.displayname),
      cst_encode_membership(raw.membership)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_message_content(MessageContent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is MessageContent_CallEncryptionKeys) {
      return [
        0,
        cst_encode_Map_String_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
            raw.body)
      ].jsify()!;
    }
    if (raw is MessageContent_Text) {
      return [1, cst_encode_String(raw.body)].jsify()!;
    }
    if (raw is MessageContent_Image) {
      return [2, cst_encode_String(raw.body)].jsify()!;
    }
    if (raw is MessageContent_Video) {
      return [3, cst_encode_String(raw.body)].jsify()!;
    }
    if (raw is MessageContent_Sticker) {
      return [4, cst_encode_String(raw.body)].jsify()!;
    }
    if (raw is MessageContent_Audio) {
      return [5, cst_encode_String(raw.body)].jsify()!;
    }
    if (raw is MessageContent_Notice) {
      return [6, cst_encode_String(raw.body)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny? cst_encode_opt_Map_String_sync_response_invited_room_None(
      Map<String, SyncResponseInvitedRoom>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_Map_String_sync_response_invited_room_None(raw);
  }

  @protected
  JSAny? cst_encode_opt_Map_String_sync_response_joined_room_None(
      Map<String, SyncResponseJoinedRoom>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_Map_String_sync_response_joined_room_None(raw);
  }

  @protected
  JSAny? cst_encode_opt_Map_String_u_64_None(Map<String, BigInt>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_Map_String_u_64_None(raw);
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  int?
      cst_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            raw);
  }

  @protected
  bool? cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_room_encryption_state(
      RoomEncryptionState? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_room_encryption_state(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_sync_response_invite_state(
      SyncResponseInviteState? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_sync_response_invite_state(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_sync_response_rooms(
      SyncResponseRooms? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_sync_response_rooms(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_sync_response_state(
      SyncResponseState? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_sync_response_state(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_sync_response_timeline(
      SyncResponseTimeline? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_sync_response_timeline(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_sync_response_to_device(
      SyncResponseToDevice? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_sync_response_to_device(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  JSAny?
      cst_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          List<Event>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
            raw);
  }

  @protected
  JSAny? cst_encode_opt_list_stripped_state_event(
      List<StrippedStateEvent>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_stripped_state_event(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_to_device_event(List<ToDeviceEvent>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_to_device_event(raw);
  }

  @protected
  JSAny
      cst_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
          (String, Room) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.$1),
      cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          raw.$2)
    ].jsify()!;
  }

  @protected
  JSAny
      cst_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          (String, Value) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.$1),
      cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          raw.$2)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_string_event_content((String, EventContent) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.$1), cst_encode_event_content(raw.$2)]
        .jsify()!;
  }

  @protected
  JSAny
      cst_encode_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          (String, Value?) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.$1),
      cst_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          raw.$2)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_string_string_opt_string(
      (String, String, String?) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.$1),
      cst_encode_String(raw.$2),
      cst_encode_opt_String(raw.$3)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_string_sync_response_invited_room(
      (String, SyncResponseInvitedRoom) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.$1),
      cst_encode_sync_response_invited_room(raw.$2)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_string_sync_response_joined_room(
      (String, SyncResponseJoinedRoom) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.$1),
      cst_encode_sync_response_joined_room(raw.$2)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_string_u_64((String, BigInt) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.$1), cst_encode_u_64(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_stripped_state_event(StrippedStateEvent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.sender),
      cst_encode_String(raw.eventType),
      cst_encode_String(raw.stateKey),
      cst_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          raw.content)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response(SyncResponse raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.nextBatch),
      cst_encode_opt_Map_String_u_64_None(raw.deviceOneTimeKeysCount),
      cst_encode_opt_box_autoadd_sync_response_to_device(raw.toDevice),
      cst_encode_opt_box_autoadd_sync_response_rooms(raw.rooms)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_invite_state(SyncResponseInviteState raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_opt_list_stripped_state_event(raw.events)].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_invited_room(SyncResponseInvitedRoom raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_sync_response_invite_state(raw.inviteState)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_joined_room(SyncResponseJoinedRoom raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_sync_response_state(raw.state),
      cst_encode_opt_box_autoadd_sync_response_timeline(raw.timeline)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_rooms(SyncResponseRooms raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_Map_String_sync_response_joined_room_None(raw.join),
      cst_encode_opt_Map_String_sync_response_invited_room_None(raw.invite),
      cst_encode_opt_Map_String_sync_response_joined_room_None(raw.leave)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_state(SyncResponseState raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          raw.events)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_timeline(SyncResponseTimeline raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          raw.events),
      cst_encode_opt_box_autoadd_bool(raw.limited),
      cst_encode_opt_String(raw.prevBatch)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sync_response_to_device(SyncResponseToDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_opt_list_to_device_event(raw.events)].jsify()!;
  }

  @protected
  JSAny cst_encode_to_device_event(ToDeviceEvent raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.sender),
      cst_encode_String(raw.eventType),
      cst_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          raw.content)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
      Event raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
      MatrixApi raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
      MatrixClient raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
      MlsCrypto raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
      MlsGroup raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
      Room raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      Value raw);

  @protected
  int cst_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
      MatrixClient raw);

  @protected
  int cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
      MatrixClient raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
      Event raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
      MatrixApi raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
      MatrixClient raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
      MlsCrypto raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
      MlsGroup raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
      Room raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      Value raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_membership(Membership raw);

  @protected
  int cst_encode_room_encryption_state(RoomEncryptionState raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          Event self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          MatrixApi self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          MatrixClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          MlsCrypto self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          MlsGroup self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          Room self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          MatrixClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          MatrixClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom_None(
          Map<String, Room> self, SseSerializer serializer);

  @protected
  void
      sse_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          Map<String, Value> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_event_content_None(
      Map<String, EventContent> self, SseSerializer serializer);

  @protected
  void
      sse_encode_Map_String_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
          Map<String, Value?> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_sync_response_invited_room_None(
      Map<String, SyncResponseInvitedRoom> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_sync_response_joined_room_None(
      Map<String, SyncResponseJoinedRoom> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_u_64_None(
      Map<String, BigInt> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          Event self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          MatrixApi self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          MatrixClient self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          MlsCrypto self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          MlsGroup self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          Room self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_content(
      CreateContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_decrypted_message(
      DecryptedMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_encrypted_content(
      EncryptedContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_encryption_content(
      EncryptionContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_event_content(
      EventContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_member_content(
      MemberContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message_content(
      MessageContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_room_encryption_state(
      RoomEncryptionState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_response_invite_state(
      SyncResponseInviteState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_response_rooms(
      SyncResponseRooms self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_response_state(
      SyncResponseState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_response_timeline(
      SyncResponseTimeline self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_response_to_device(
      SyncResponseToDevice self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_create_content(CreateContent self, SseSerializer serializer);

  @protected
  void sse_encode_decrypted_message(
      DecryptedMessage self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_content(
      EncryptedContent self, SseSerializer serializer);

  @protected
  void sse_encode_encryption_content(
      EncryptionContent self, SseSerializer serializer);

  @protected
  void sse_encode_event_content(EventContent self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          List<Event> self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          List<Room> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
          List<(String, Room)> self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          List<(String, Value)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_event_content(
      List<(String, EventContent)> self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          List<(String, Value?)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_sync_response_invited_room(
      List<(String, SyncResponseInvitedRoom)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_sync_response_joined_room(
      List<(String, SyncResponseJoinedRoom)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_u_64(
      List<(String, BigInt)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_stripped_state_event(
      List<StrippedStateEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_to_device_event(
      List<ToDeviceEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_member_content(MemberContent self, SseSerializer serializer);

  @protected
  void sse_encode_membership(Membership self, SseSerializer serializer);

  @protected
  void sse_encode_message_content(
      MessageContent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_sync_response_invited_room_None(
      Map<String, SyncResponseInvitedRoom>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_sync_response_joined_room_None(
      Map<String, SyncResponseJoinedRoom>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_u_64_None(
      Map<String, BigInt>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          Value? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_room_encryption_state(
      RoomEncryptionState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_response_invite_state(
      SyncResponseInviteState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_response_rooms(
      SyncResponseRooms? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_response_state(
      SyncResponseState? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_response_timeline(
      SyncResponseTimeline? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sync_response_to_device(
      SyncResponseToDevice? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          List<Event>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_stripped_state_event(
      List<StrippedStateEvent>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_to_device_event(
      List<ToDeviceEvent>? self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_room(
          (String, Room) self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          (String, Value) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_event_content(
      (String, EventContent) self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_string_opt_box_autoadd_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
          (String, Value?) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string_opt_string(
      (String, String, String?) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_sync_response_invited_room(
      (String, SyncResponseInvitedRoom) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_sync_response_joined_room(
      (String, SyncResponseJoinedRoom) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_u_64(
      (String, BigInt) self, SseSerializer serializer);

  @protected
  void sse_encode_room_encryption_state(
      RoomEncryptionState self, SseSerializer serializer);

  @protected
  void sse_encode_stripped_state_event(
      StrippedStateEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response(SyncResponse self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_invite_state(
      SyncResponseInviteState self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_invited_room(
      SyncResponseInvitedRoom self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_joined_room(
      SyncResponseJoinedRoom self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_rooms(
      SyncResponseRooms self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_state(
      SyncResponseState self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_timeline(
      SyncResponseTimeline self, SseSerializer serializer);

  @protected
  void sse_encode_sync_response_to_device(
      SyncResponseToDevice self, SseSerializer serializer);

  @protected
  void sse_encode_to_device_event(ToDeviceEvent self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_access_token(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_access_token(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_api(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_api(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_crypto(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_crypto(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_device_id(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_device_id(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_homeserver_url(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_homeserver_url(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_prev_batch(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_prev_batch(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_rooms(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_rooms(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_sent_messages_cache(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_sent_messages_cache(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_transaction_id(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_transaction_id(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_user_id(
              int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_get_user_id(
                  that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_access_token(
              int that, String access_token) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_access_token(
                  that, access_token);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_api(
              int that, int api) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_api(
                  that, api);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_crypto(
              int that, int crypto) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_crypto(
                  that, crypto);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_device_id(
              int that, String device_id) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_device_id(
                  that, device_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_homeserver_url(
              int that, String homeserver_url) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_homeserver_url(
                  that, homeserver_url);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_prev_batch(
              int that, String? prev_batch) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_prev_batch(
                  that, prev_batch);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_rooms(
              int that, JSAny rooms) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_rooms(
                  that, rooms);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_sent_messages_cache(
              int that, JSAny sent_messages_cache) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_sent_messages_cache(
                  that, sent_messages_cache);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_transaction_id(
              int that, String transaction_id) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_transaction_id(
                  that, transaction_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_user_id(
              int that, String user_id) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_auto_accessor_set_user_id(
                  that, user_id);

  void wire__crate__client__client__MatrixClient_claim_key_packages(
          NativePortType port_, int that, String user_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_claim_key_packages(
          port_, that, user_id);

  void wire__crate__client__client__MatrixClient_create_key_package(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__client__client__MatrixClient_create_key_package(
          port_, that);

  void wire__crate__client__client__MatrixClient_create_message(
          NativePortType port_, int that, String group_id, String message) =>
      wasmModule.wire__crate__client__client__MatrixClient_create_message(
          port_, that, group_id, message);

  void wire__crate__client__client__MatrixClient_create_mls_group(
          NativePortType port_, int that, String name) =>
      wasmModule.wire__crate__client__client__MatrixClient_create_mls_group(
          port_, that, name);

  void wire__crate__client__client__MatrixClient_create_room(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__client__client__MatrixClient_create_room(
          port_, that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_get_room_list(int that) =>
          wasmModule
              .wire__crate__client__client__MatrixClient_get_room_list(that);

  void wire__crate__client__client__MatrixClient_group_is_found(
          NativePortType port_, int that, String group_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_group_is_found(
          port_, that, group_id);

  void wire__crate__client__client__MatrixClient_invite(
          NativePortType port_, int that, String room_id, String user_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_invite(
          port_, that, room_id, user_id);

  void wire__crate__client__client__MatrixClient_invite_to_mls_group(
          NativePortType port_,
          int that,
          String group_id,
          JSAny key_packages_base64) =>
      wasmModule.wire__crate__client__client__MatrixClient_invite_to_mls_group(
          port_, that, group_id, key_packages_base64);

  void wire__crate__client__client__MatrixClient_join_room(
          NativePortType port_, int that, String room_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_join_room(
          port_, that, room_id);

  void wire__crate__client__client__MatrixClient_leave_room(
          NativePortType port_, int that, String room_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_leave_room(
          port_, that, room_id);

  void wire__crate__client__client__MatrixClient_login(NativePortType port_,
          String homeserver_url, String username, String password) =>
      wasmModule.wire__crate__client__client__MatrixClient_login(
          port_, homeserver_url, username, password);

  void wire__crate__client__client__MatrixClient_main_thread_sleep(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__client__client__MatrixClient_main_thread_sleep(
          port_, that);

  void wire__crate__client__client__MatrixClient_matrix_client_crypto(
          NativePortType port_,
          String homeserver_url,
          String user_id,
          String device_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_matrix_client_crypto(
          port_, homeserver_url, user_id, device_id);

  void wire__crate__client__client__MatrixClient_merge_pending_commit(
          NativePortType port_, int that, String group_id) =>
      wasmModule.wire__crate__client__client__MatrixClient_merge_pending_commit(
          port_, that, group_id);

  void wire__crate__client__client__MatrixClient_process_mls_message(
          NativePortType port_, int that, String cipher_text) =>
      wasmModule.wire__crate__client__client__MatrixClient_process_mls_message(
          port_, that, cipher_text);

  void wire__crate__client__client__MatrixClient_publish_key_packages(
          NativePortType port_, int that, int count) =>
      wasmModule.wire__crate__client__client__MatrixClient_publish_key_packages(
          port_, that, count);

  void wire__crate__client__client__MatrixClient_room_encryption_state(
          NativePortType port_, int that, String room_id) =>
      wasmModule
          .wire__crate__client__client__MatrixClient_room_encryption_state(
              port_, that, room_id);

  void wire__crate__client__client__MatrixClient_rooms_safe(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__client__client__MatrixClient_rooms_safe(
          port_, that);

  void wire__crate__client__client__MatrixClient_send_message(
          NativePortType port_, int that, String room_id, String body) =>
      wasmModule.wire__crate__client__client__MatrixClient_send_message(
          port_, that, room_id, body);

  void wire__crate__client__client__MatrixClient_send_mls_message(
          NativePortType port_,
          int that,
          String room_id,
          String mls_message,
          JSAny event_content,
          bool wait_for_sync_and_merge_commit) =>
      wasmModule.wire__crate__client__client__MatrixClient_send_mls_message(
          port_,
          that,
          room_id,
          mls_message,
          event_content,
          wait_for_sync_and_merge_commit);

  void wire__crate__client__client__MatrixClient_send_welcome_message(
          NativePortType port_, int that, String user_id, String body) =>
      wasmModule.wire__crate__client__client__MatrixClient_send_welcome_message(
          port_, that, user_id, body);

  void wire__crate__client__client__MatrixClient_sync(
          NativePortType port_, int that, JSAny? timeout) =>
      wasmModule.wire__crate__client__client__MatrixClient_sync(
          port_, that, timeout);

  void wire__crate__client__client__MatrixClient_unsafe_logout(
          NativePortType port_, int that) =>
      wasmModule.wire__crate__client__client__MatrixClient_unsafe_logout(
          port_, that);

  void wire__crate__crypto__mls_crypto__decrypted_message_content(
          NativePortType port_, JSAny that) =>
      wasmModule.wire__crate__crypto__mls_crypto__decrypted_message_content(
          port_, that);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
              ptr);
}

@JS('mls_wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_access_token(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_api(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_crypto(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_device_id(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_homeserver_url(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_prev_batch(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_rooms(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_sent_messages_cache(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_transaction_id(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_get_user_id(
          int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_access_token(
          int that, String access_token);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_api(
          int that, int api);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_crypto(
          int that, int crypto);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_device_id(
          int that, String device_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_homeserver_url(
          int that, String homeserver_url);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_prev_batch(
          int that, String? prev_batch);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_rooms(
          int that, JSAny rooms);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_sent_messages_cache(
          int that, JSAny sent_messages_cache);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_transaction_id(
          int that, String transaction_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_auto_accessor_set_user_id(
          int that, String user_id);

  external void wire__crate__client__client__MatrixClient_claim_key_packages(
      NativePortType port_, int that, String user_id);

  external void wire__crate__client__client__MatrixClient_create_key_package(
      NativePortType port_, int that);

  external void wire__crate__client__client__MatrixClient_create_message(
      NativePortType port_, int that, String group_id, String message);

  external void wire__crate__client__client__MatrixClient_create_mls_group(
      NativePortType port_, int that, String name);

  external void wire__crate__client__client__MatrixClient_create_room(
      NativePortType port_, int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__client__client__MatrixClient_get_room_list(int that);

  external void wire__crate__client__client__MatrixClient_group_is_found(
      NativePortType port_, int that, String group_id);

  external void wire__crate__client__client__MatrixClient_invite(
      NativePortType port_, int that, String room_id, String user_id);

  external void wire__crate__client__client__MatrixClient_invite_to_mls_group(
      NativePortType port_,
      int that,
      String group_id,
      JSAny key_packages_base64);

  external void wire__crate__client__client__MatrixClient_join_room(
      NativePortType port_, int that, String room_id);

  external void wire__crate__client__client__MatrixClient_leave_room(
      NativePortType port_, int that, String room_id);

  external void wire__crate__client__client__MatrixClient_login(
      NativePortType port_,
      String homeserver_url,
      String username,
      String password);

  external void wire__crate__client__client__MatrixClient_main_thread_sleep(
      NativePortType port_, int that);

  external void wire__crate__client__client__MatrixClient_matrix_client_crypto(
      NativePortType port_,
      String homeserver_url,
      String user_id,
      String device_id);

  external void wire__crate__client__client__MatrixClient_merge_pending_commit(
      NativePortType port_, int that, String group_id);

  external void wire__crate__client__client__MatrixClient_process_mls_message(
      NativePortType port_, int that, String cipher_text);

  external void wire__crate__client__client__MatrixClient_publish_key_packages(
      NativePortType port_, int that, int count);

  external void wire__crate__client__client__MatrixClient_room_encryption_state(
      NativePortType port_, int that, String room_id);

  external void wire__crate__client__client__MatrixClient_rooms_safe(
      NativePortType port_, int that);

  external void wire__crate__client__client__MatrixClient_send_message(
      NativePortType port_, int that, String room_id, String body);

  external void wire__crate__client__client__MatrixClient_send_mls_message(
      NativePortType port_,
      int that,
      String room_id,
      String mls_message,
      JSAny event_content,
      bool wait_for_sync_and_merge_commit);

  external void wire__crate__client__client__MatrixClient_send_welcome_message(
      NativePortType port_, int that, String user_id, String body);

  external void wire__crate__client__client__MatrixClient_sync(
      NativePortType port_, int that, JSAny? timeout);

  external void wire__crate__client__client__MatrixClient_unsafe_logout(
      NativePortType port_, int that);

  external void wire__crate__crypto__mls_crypto__decrypted_message_content(
      NativePortType port_, JSAny that);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEvent(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixApi(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCrypto(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsGroup(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoom(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          int ptr);
}
